filebeat.inputs:
- type: log
  enabled: true
  paths:
  - /var/log/nginx/access.log
  fields:
    source: nginx
  fields_under_root: true

output.kafka:
  hosts: [ "kafka:9092" ]
  topic: "nginx_logs"
  codec.format:
    string: '%{[message]}'
  required_acks: 1
  max_message_bytes: 1000000
